In [1]:
#Numpy

In [2]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

AttributeError: ignored

In [11]:
# zeros,ones,empty를 사용하여 배열을 생성
print(np.zeros((3,3)))
print(np.ones((2,2)))
print(np.empty((3,3)))  # 이전에 사용한 배열이 나옴

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1.76154798e-316 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 6.93680424e-310]]


In [15]:
# arange를 사용하여 특정 범위의 함수 생성 
print(np.arange(0,10))
print(np.arange(0,10,2))
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [22]:
# ndarray를 사용하여 배열의 모양, 차수, 데이터 타입 확인
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim) #차원확인
print(arr.shape) #모양확인
print(arr.dtype) #배열 속 데이터 타입 확인

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64


In [27]:
# ndarray 배열의 타입 변환
arr_int = np.array([1,2,3,4])
print(arr_int.dtype)
arr_float = arr_int.astype(np.float64)
print(arr_float.dtype)

int64
float64


In [31]:
arr_str=np.array(["1","2","3","4"])
print(arr_str.dtype)
arr_strToInt=arr_str.astype(np.int64)
print(arr_strToInt.dtype)

<U1
int64


In [38]:
# 배열의 연산
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [41]:
# ndarray 배열 슬라이싱 하기
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr_1 = arr[:2,1:3]
print(arr_1)
print(arr[0,2])

[[2 3]
 [5 6]]
3


In [43]:
idx = arr > 3
print(idx)
print(arr[idx])

[[False False False]
 [ True  True  True]
 [ True  True  True]]
[4 5 6 7 8 9]


In [57]:
redwine = np.loadtxt(fname="winequality-red.csv", delimiter=";", skiprows=1)
print(redwine)
print(redwine[2,:])

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
[7.80e+00 7.60e-01 4.00e-02 2.30e+00 9.20e-02 1.50e+01 5.40e+01 9.97e-01
 3.26e+00 6.50e-01 9.80e+00 5.00e+00]


In [58]:
# 기초 통계 함수 (sum 합계, mean 평균, std**2 표준편차, var 분산, min 최소, max 최대)
print(redwine.sum())
print(redwine.sum(axis=0)) # axis=0: 세로로 계산, axis=1: 가로로 계산
print(redwine.mean())
print(redwine.mean(axis=0))
print(redwine[:,0].mean())
print(redwine.std()**2)
print(redwine.var())
print(redwine.min())
print(redwine.max())

152084.78194
[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
7.926036165311652
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]
8.31963727329581
256.993249477214
256.993249477214
0.0
289.0


9.296083333333332
